Update CMakeLists.txt
- add `opencv_imgcodecs` to `target_link_libraries` for OpenCV 3.0 (fixing error:
    /usr/bin/ld: libBING.a(Objectness.cpp.o): undefined reference to symbol     '_ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE'
    /usr/local/lib/libopencv_imgcodecs.so.3.0: error adding symbols: DSO missing from command line)

- re-organize library compile order 
    - previously the LibLinear was compiled as library but not used; the BING was not considered as library
    - now LibLinear and BING are compiled as libraries and linked to a single `main.cpp`